name: Build and publish to npm

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: latest-release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/microsoft/vscode/releases/latest | jq -r .tag_name)
          echo "Latest release tag is $latest_release"
          echo "LATEST_RELEASE=v$latest_release" >> $GITHUB_ENV

      - name: Checkout Visual Studio Code
        uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: ${{ env.LATEST_RELEASE }}
          path: vscode

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd vscode
          npm install

      - name: Build css language server
        run: |
          cd vscode/extensions/css-language-features/server
          npm run compile

      - name: Build html language server
        run: |
          cd vscode/extensions/html-language-features/server
          npm run compile

      - name: Build json language server
        run: |
          cd vscode/extensions/json-language-features/server
          npm run compile

      - name: Copy files
        run: |
          mkdir bin
          cp vscode/extensions/css-language-features/server/dist/node/* bin/
          cp vscode/extensions/html-language-features/server/dist/node/* bin/
          cp vscode/extensions/json-language-features/server/dist/node/* bin/
          rm -rf vscode

      - name: Publish Package to npmjs
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}