name: Extract and Publish to npm

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 2' 
  # push:
  #   tags:
  #     - "v*"

jobs:
  extract-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract and Publish new version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          chmod +x ./script.sh
          ./script.sh

          git add package.json
          git commit --amend -m "$commit_message"
          git push --force-with-lease && git push --tags