name: Extract and Publish to npm

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 2' 
  # push:
  #   tags:
  #     - "v*"

jobs:
  extract-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for updates and extract files
        id: extract
        run: |
          chmod +x ./script.sh
          if ./script.sh; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and commit
        if: steps.extract.outputs.has_updates == 'true'
        run: |
          # Commit the package.json metadata changes
          git add package.json
          git commit -m "chore: update vscode language server versions"
          
          # Manually bump version in package.json
          npm version patch --no-git-tag-version
          
          # Commit the version bump
          NEW_VERSION=$(jq -r .version package.json)
          git add package.json
          git commit -m "chore: release v${NEW_VERSION}"
          git tag "v${NEW_VERSION}"

      - name: Publish to npm
        if: steps.extract.outputs.has_updates == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Push changes
        if: steps.extract.outputs.has_updates == 'true'
        run: git push --atomic origin HEAD:${{ github.ref_name }} --tags